---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - python
  eslint:
    enabled: true
    config:
      extensions:
        - .es6
  fixme:
    enabled: true
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
    config:
      python_version: 2
ratings:
  paths:
    - "**.css"
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.py"
exclude_paths:
  - "tests/"
  - "testing/"
  - "static/"
  - "pytz/"
